### ISSUE TITLE
Read/Write Fİle

### ISSUE THREAD

**Issue by YilmazGursoy** [YilmazGursoy/Motion#1]
![bug](https://cloud.githubusercontent.com/assets/9751498/14451150/5f8c61ec-008d-11e6-8f0c-7bdf0574fdaa.png)
Resimde gördügüm hata ile karsılastım,
Projeyi calistirirken yapmamız gereken dosya ekleme yada direction' unu degistirme hatası olabilir

**Comment by AnilOsmanTur** [comment]
kodu çalıştırken:
 ->>python Student..File.py --file [dosyanın adı] 
 -şeklinde çalıştırmalısın dosyanın adı ornek olarak paylaştığım dosya adını "--file"  dan sonra herhangi bir ek karakter olamadan "last..blabla..txt" olarak eklemek gerekiyor.
